import numpy as np
ele_1 = eval (input("Enter list 1\n"))
ele_2 = eval (input("Enter list 2\n"))
arr_1 = np.array(ele_1,dtype=np.str)
arr_2 = np.array(ele_2,dtype=np.str)
print("\nArray1:")
print(arr_1)
print("Array2:")
print(arr_2)
equal = np.char.equal(arr_1,arr_2)
print("\nEqual test:",equal)
not_equal = np.char.not_equal(arr_1,arr_2)
print("\nNot equal test:",not_equal)
less_equal= np.char.less_equal(arr_1,arr_2)
print("\nLess equal test:",less_equal)
great_equal= np.char.greater_equal(arr_1,arr_2)
print("\nGreater equal test:",great_equal)
less = np.char.less(arr_1,arr_2)
print("\nLess test:",less)

